### ISSUE TITLE
TypeScript type definition

### ISSUE THREAD

**Issue by tyrone-sudeium** [AndrewBarba/apns2#12]
I've written a pretty comprehensive type definition for this module (at least the 2.0.0 version of it), was just wondering what you'd prefer I do with it?

## 1. Pull Request this repo
I could open a pull request to this repo, adding the `.d.ts` type definition, as well as adding a types reference to the `package.json`. This would give the best user experience for TypeScript users since they'd just install this node module the usual way and TypeScript would automatically pick up the types with zero intervention. It would also give a better JavaScript development experience if the user is using Visual Studio Code since the autocomplete would pick up the type definitions.

However, this means it'd be in the official repo and you would have to keep them up to date if you ever make any changes to the exported interface for this module. I'm not sure how familiar with TypeScript you are, this isn't particularly arduous, but if you haven't done it before it can be confusing.

## 2. Submit to DefinitelyTyped
I could submit these to the DefinitelyTyped repo. This means the TypeScript community would essentially have to maintain the type definitions. TypeScript users would have to manually install them by doing `npm install @types/apns2`, and at any time they may be out of date or incomplete.

Doing it this way keeps the type definitions totally third party and you don't ever have to really think about it again.

## 3. Keep it to myself
I could just go away and keep the type definitions to myself. This is a good option if you're fundamentally against the entire concept of TypeScript for philosophical reasons.

**Comment by AndrewBarba** [comment]
Awesome! Open up the PR, I'll gladly maintain in repo, I use VScode exclusively for node dev and always appreciate when the definitions are there
