### ISSUE TITLE
Types in package.json

### ISSUE THREAD

**Issue by tyrone-sudeium** [AndrewBarba/apns2#14]
Hey, I noticed that the type definitions fell out of the `package.json` at some point (probably during the merge conflict resolution from the http2 branch). Could you please add this back to the `package.json`, just under `"main": "lib/apns.js"`:

```"types": "lib/apns.d.ts"```

It'll probably break TypeScript without it.

**Comment by AndrewBarba** [comment]
Ah sorry, figured I missed something. Will add now

**Comment by AndrewBarba** [comment]
Pushing 3.0.1
