### ISSUE TITLE
Using SPDY, receiving 'Got RST: REFUSED_STREAM'

### ISSUE THREAD

**Issue by DanielAskTia** [AndrewBarba/apns2#15]
When sending multiple notifications using SPDY, I'm receiving the error `Got RST: REFUSED_STREAM`.  This error immediately goes away when I change from node 6.9.1 (i.e. AWS' node version) to 8.6.0 using --expose-http2.

Edit: it also goes away when I go from 8.6.0 _without_ --expose-http2 to 8.6.0 with --expose-http2.

**Comment by AndrewBarba** [comment]
Yeah this makes sense, node-spy and node-http2 never worked very reliably. Now that Node v8.9.0 LTS is released, you can update to that and no longer need the `--expose-http2` argument since it's enabled by default
