### ISSUE TITLE
429 - TooManyProviderTokenUpdates errors received on long-running instances 

### ISSUE THREAD

**Issue by DanielAskTia** [AndrewBarba/apns2#16]
We've got an instance of AWS running code that uses APNS2 and, by and large, it's flawless.  The only problem we've experienced is that long-running instances seem to start receiving 429 `TooManyProviderTokenUpdates` errors.  The simple solution is to restart the server, but in that case "solution" isn't exactly what it is.  Restarting the server weekly solves the problem too, so it seems like the problem is only experienced with many notifications sent or long uptime (i.e. "weeks").

Any thoughts the diagnosis of this problem?

**Comment by AndrewBarba** [comment]
Hey thanks for bringing this up! I haven't seen it before, but seems like Apple wants us to reset the signing token a lot closer to the expiration time. I just v4.0.2 that does this, let me know if that helps

https://github.com/AndrewBarba/apns2/releases/tag/4.0.2

**Comment by AndrewBarba** [comment]
Ah, and just came across this: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

<img width="785" alt="screen shot 2018-06-21 at 6 17 37 pm" src="https://user-images.githubusercontent.com/1316152/41748323-68b0f5d0-757f-11e8-8d1d-8f78a1a30d02.png">

Before I was updating at 20 minute intervals, which explains why you were seeing this so infrequently, timing probably had to be just right to see it.

**Comment by DanielAskTia** [comment]
I had read the same passage, and figured it might be that apns2 was set to 20 minutes.  The only part I couldn't figure out: why it wouldn't fail w/ fair regularity off the bat.

Regardless, I'll update my fork and follow up ... in a couple weeks when it normally would cause me issues w/ 429s.

**Comment by DanielAskTia** [comment]
I apologize for not responding until after you closed it.  So far, we've seen no further issues with 429s.  I'll reply back later if any are found!

**Comment by AndrewBarba** [comment]
No problem! Figured you could just re-open if it happens again
