### ISSUE TITLE
Support Notification `thread-id`

### ISSUE THREAD

**Issue by grippy** [AndrewBarba/apns2#19]
It would be nice if Notification options defined `threadId` as a possible property.

```
new Notification(token, {"threadId": "some id"});
```

See docs here:
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html

However, as this module is currently written, it is possible to get around this by setting the `thread-id` on the options.aps object.

Anyway, seems like a simple add. I'll submit a PR for this feature.

**Comment by AndrewBarba** [comment]
Good catch, let me know if this looks good and I'll merge and publish: https://github.com/AndrewBarba/apns2/pull/20

**Comment by AndrewBarba** [comment]
Just published as v6.1.0 https://www.npmjs.com/package/apns2
