### ISSUE TITLE
Support VoIP push by using correct apns-push-type

### ISSUE THREAD

**Issue by bfelbo** [AndrewBarba/apns2#23]
We're getting `400 - InvalidPushType` for our VoIP push because the `apns-push-type` is not set to `voip` as it should. See: 
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

The simplest way to implement this is likely to detect whether it's a voip push from the topic. If it ends with `.voip`, it's a VoIP push and the push type should be set accordingly.

**Comment by AndrewBarba** [comment]
https://github.com/AndrewBarba/apns2/commit/9ad289adef910ca6d7d8a43c1e92edff3ca0e0aa
