### ISSUE TITLE
Missing Topic

### ISSUE THREAD

**Issue by i2joseph** [AndrewBarba/apns2#3]
Hi,

I am getting error Missing Topic. From the table 6-6 Apple error reason key saying that the apns-topic header of the request was not specified and was required. How I can add that?

Thanks.

**Comment by i2joseph** [comment]
I found it. Thanks.

**Comment by AndrewBarba** [comment]
👍 I will document that better, thanks!

**Comment by i2joseph** [comment]
Hi Andrew. This is unrelated question with this matter. I am just wondering if you know how to handle the inactive devices? Thanks.

**Comment by AndrewBarba** [comment]
Hey Joseph, I actually have an example of this in the read me. Essentially you should always try and send a push notification and listen for any errors. If you get a bad device token error then you know you can remove it from your database, or handle accordingly.

```
const errors = APNS.errors;

// Listen for a specific error
client.on(errors.badDeviceToken, err => {
  // Handle accordingly...
  // Perhaps delete token from your database
  console.error(err.reason, err.statusCode, err.notification.deviceToken);
});
```

**Comment by i2joseph** [comment]
Interesting. I used to use the Java-APNS, https://github.com/notnoop/java-apns and I need to call another function to get the list of inactive devices. Okay Thank you so much for your information.

**Comment by AndrewBarba** [comment]
Yeah I don't like that model for Node. Node is event based, I'd rather embrace that and listen for the inactive event and act accordingly. Otherwise you are polling that endpoint at some decided interval. It works, I'm sure, but not a pattern I want in this library
