### ISSUE TITLE
Possible typo in typings?

### ISSUE THREAD

**Issue by ShaharHD** [AndrewBarba/apns2#30]
https://github.com/AndrewBarba/apns2/blob/e6d6fbb93ef7e121d96335f35ee6c25e13de4ebd/index.d.ts#L7

Seems it should be `void` and not `Void`

**Comment by AndrewBarba** [comment]
Ah damn, I’ve been writing a lot more Swift than JS/TS. Will get this fixed

**Comment by ShaharHD** [comment]
#31 created

It kept giving me errors on `tsc`

**Comment by ShaharHD** [comment]
FYI, it seems the auto build fails because of mismatch between the wrecker file and the `package.json`.

Is there a reason you're looking for `10.16` and not simply `10.x` ?

My suggestion in any case would be to update the wrecker file file to `box: node:10` and in the `package.json` to 

```json
  "engines": {
    "node": "10.x"
  },
```

**Comment by AndrewBarba** [comment]
Releasing as 8.5.0
