### ISSUE TITLE
Codebase Issues

### ISSUE THREAD

**Issue by trevh3** [AndrewBarba/apns2#33]
Looking through your code before I used the package, and I wanted to double-check some stuff with you.
```
  async connect() {
    return new Promise((resolve, reject) => {
      let session = http2.connect(this._url)
      session.once('error', reject)
      session.once('socketError', reject)
      session.once('connect', () => {
        this._connected(session)
        resolve(this)
      })
    })
  }

  _connected(session) {
    session.on('close', () => this.destroy())
    session.on('frameError', () => this.destroy())
    session.on('goaway', () => this.destroy())
    session.on('socketError', () => this.destroy())
    session.on('timeout', () => this.destroy())
    this._session = session
    this._ready = true
  }
}
```

1.  Did you mean to say `frameError` instead of `socketError`? I cannot find a reference to `socketError` in the docs. `frameError` is referenced in the nodejs http2 core, but the comments say it is "exceedingly rare". 
[docs](https://nodejs.org/api/http2.html#http2_event_frameerror)
[code](https://github.com/nodejs/node/blob/1aa847f7438407b78cc0d1f9eab96adcfe9ff9df/lib/internal/http2/core.js#L565)
2. In `connect()`, Once the promise is fulfilled with `resolve(this)`, you cannot `reject` the fulfilled promise. When `session.once('error')` and `session.once('socketError')` are fired, `reject` should have no effect. Those two lines won't do anything, even though the event handlers should exist over the life of the socket.
3. This is merely a stylistic note, but in `connect()`, the third argument to `http2.connect` is a callback that executes when `connect` event fires. Docs say "User code will typically not listen for this event directly."
[docs](https://nodejs.org/api/http2.html#http2_event_connect)
[code](https://github.com/nodejs/node/blob/1aa847f7438407b78cc0d1f9eab96adcfe9ff9df/lib/internal/http2/core.js#L3066)
4. In `_connected()`, `socketError` doesn't look like an event that can be fired. Can be removed from `_connected()` function.
5. In `_connected()`, According to the docs, the http2 session will be shut down automatically when the `goaway` frame is received. Listening for the `goaway` event and then calling destroy doesn't give the core the chance to gracefully end open streams on the socket.
[docs](https://nodejs.org/api/http2.html#http2_event_goaway) [code](https://github.com/nodejs/node/blob/1aa847f7438407b78cc0d1f9eab96adcfe9ff9df/lib/internal/http2/core.js#L620)
6. In `_connected()`, You listen for the `timeout` event, but according to the docs, this event is only fired if you call http2session.setTimeout, which it doesn't look like you do. You do set a timeout on the http2streamrequest, but listening for that only kills the stream, not the socket.
[docs](https://nodejs.org/api/http2.html#http2_event_timeout)
[docs](https://nodejs.org/api/http2.html#http2_request_settimeout_msecs_callback)
7. None of the functions in `http2-client.js` need to be `async`.
8. The `close` event is emitted after `destroy` event.

**Comment by trevh3** [comment]
9. No need to maintain a ready boolean because the http2 core handles buffering incoming requests until the socket is opened. It also internally maintains ready using the `destroyed` flag.
[https://nodejs.org/docs/latest-v14.x/api/http2.html#http2_creation](http2session lifecycle)
[https://nodejs.org/docs/latest-v14.x/api/http2.html#http2_http2session_destroyed](destroyed flag)

**Comment by trevh3** [comment]
Also, am I correct in understanding that you're utilizing tarn to set up and tear down http2 (TLS) connections - one for each message up to max connections, instead of using a single connection to send many messages via streams? Apple explicitly states that this is bad form, and it's very expensive setting up that many connections!

**Comment by trevh3** [comment]
11. In `request`, body is defined twice - once in the arguments and once in the event emitter for response.

**Comment by trevh3** [comment]
@AndrewBarba

**Comment by AndrewBarba** [comment]
Another PR to handle session errors: https://github.com/AndrewBarba/apns2/pull/40

**Comment by AndrewBarba** [comment]
Closing this now that v9.1 is released: https://github.com/AndrewBarba/apns2/releases

I think v9 is a substantially  better product than v8 and anything before it, but of course feel free to raise more issues/concerns/suggestions.
