### ISSUE TITLE
Connection Timeouts

### ISSUE THREAD

**Issue by cbratschi** [AndrewBarba/apns2#38]
I am trying to send > 20k push messages using this library and am seeing timeouts:

Error: http2: timeout connecting to https://api.push.apple.com/
    at ClientHttp2Stream.<anonymous> (/node_modules/apns2/lib/http2-client.js:143:38)
    at ClientHttp2Stream.emit (events.js:322:22)
    at ClientHttp2Stream._onTimeout (internal/http2/core.js:1915:10)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

In this case the error handling seems to be broken too. The returned error objects do not contain a status or reason.

**Comment by AndrewBarba** [comment]
Hi do you mind trying the latest version v9.0.0? Also what version of Node are you using and how are you sending the notifications? A sample snippet would be helpful. I'm looking to see if you are trying to send 20k in parallel of if your sending in batches/serially

**Comment by cbratschi** [comment]
Hi @AndrewBarba,

We switched to @parse/node-apn in the meantime which works fine.

Thanks,
Christoph

**Comment by cbratschi** [comment]
For each token we created a notification instance and called the send() method of the APNS client.

**Comment by AndrewBarba** [comment]
Thats good to know, thanks! I have a pretty strict timeout of 5s. I also took a look at their code and they are correctly handling some error and go away events that I am not. I'm going to implement those but obviously dont expect you to switch back, their lib certainly looks good.

**Comment by AndrewBarba** [comment]
This PR more closely matches what parse/node-apn is doing: https://github.com/AndrewBarba/apns2/pull/40

**Comment by AndrewBarba** [comment]
Closing this now that v9.1 is released: https://github.com/AndrewBarba/apns2/releases
