### ISSUE TITLE
TooManyProviderTokenUpdates (429) errors

### ISSUE THREAD

**Issue by feimosi** [AndrewBarba/apns2#44]
I've noticed we're getting `TooManyProviderTokenUpdates` errors in our app lately.
Maybe that's related to the older issue: https://github.com/AndrewBarba/apns2/issues/16, but in our case it doesn't happen on long-running instances. So far it looks random to me - in the last two weeks it happened 36 times out of over 2600 pushes sent. I don't see any correlation.

**Comment by AndrewBarba** [comment]
@feimosi  I may have a clue what's going on here.

When you create the apns instance, we start an interval that resets the token every 55 minutes. But say you create that instance but dont send a notification for 45 minutes after creating it. Its at that time that we will actually create the first token for use, and then just 10 minutes later it will get reset which is under Apple's 20 minute limit.

I'm going to put up a PR that corrects this

**Comment by AndrewBarba** [comment]
Here's a PR: https://github.com/AndrewBarba/apns2/pull/45

**Comment by feimosi** [comment]
That makes a lot of sense, thanks for addressing the issue!

**Comment by AndrewBarba** [comment]
Released https://github.com/AndrewBarba/apns2/releases/tag/9.3.0
