### ISSUE TITLE
No support for multiple notifications(Coalesced Notifications)

### ISSUE THREAD

**Issue by sumeet559** [AndrewBarba/apns2#5]
in apns2/lib/notifications/notification.js  line#105
   Object input is handled for key "data".
   An array input for key "data" may be helpful in sending many payloads in a single notification.
 Also the push notification payload size has increased to 4K.
This change may help in sending all in one I guess.
 Thanks.

**Comment by sumeet559** [comment]
apns-collapse-id support??

**Comment by AndrewBarba** [comment]
Looking into `apns-collapse-id`, thanks for bringing it up

**Comment by AndrewBarba** [comment]
Released in v1.3.0
