### ISSUE TITLE
Change signerKey to be either object or string to allow certificate passphrases

### ISSUE THREAD

**Issue by bigboypantson** [AndrewBarba/apns2#53]
We could change the signerKey to accept either string or object, then we can pass in an object with key and passphrase like the example below, `jwt.sign` accepts the following format.

`signingKey: {
      key: fs.readFileSync('/path/to/your/key.ext'),
      passphrase: 'secretpassphrase'
    }
`

I have tested this and it works with very few changes, let me know if you think this is a good idea and I will do the PR.

Thanks

**Comment by AndrewBarba** [comment]
Hey @bigboypantson sorry for the delay. This makes sense to me - feel free to open PR

**Comment by AndrewBarba** [comment]
@bigboypantson This is all set on main, I'll be releasing v10 shortly
