### ISSUE TITLE
Proxy Mode

### ISSUE THREAD

**Issue by FredyBellidoTenorio** [AndrewBarba/apns2#6]
Hi Andrew,

The current implementation does not allow usage of a proxy. This would be a great feature for those having to use apns2 behind firewalls. Are there any other suggestions on how use it in such an environment where internet access is restricted?

Thanks for you help!
Kind regards.

**Comment by AndrewBarba** [comment]
Hey thanks for bringing this up. I can expose the relevant options as described here: http://stackoverflow.com/questions/3862813/how-can-i-use-an-http-proxy-with-node-js-http-client/6781592#6781592

**Comment by FredyBellidoTenorio** [comment]
Hi Andrew,
I would like to know if your apns2 module can be used with a proxy, as the machine Where is going to be located doesn't have internet direct connection, the internet output would be made through a proxy.

**Comment by AndrewBarba** [comment]
Okay can you look at my previous comment? Have you gotten the regular `http` api to work with your use case? If so then I can expose those options and get this to work as well

**Comment by AndrewBarba** [comment]
Haven't heard back in a while, closing for now
