### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by rollarapp** [AndrewBarba/apns2#70]
AWS is now node 18, this package breaks our API CI with the old version of jwt npm... when running in a deprecated version node 16 it runs.  When is this going to be updated to support the recommended settings by AWS?? It seems it is updated frequently but never addresses this problem. We were able to send successfully today using easy-apn so we know it is not impossible.

**Comment by rollarapp** [comment]
according to npm you have 3100+ people relying on this so either you are lying or we are moving to easy-apn.

**Comment by AndrewBarba** [comment]
Game on. Let's do this. Your package is a scam trying to use curl most likely stealing certs.

**Comment by rollarapp** [comment]
Yikes! We did not publish a package... we have been waiting on your daily updates, to no avail. I checked with our CTO who... is credible to say the least. I can confidently say there are more security flaws in apns2 than easy-apn. Not coming at you, just trying to state a solution that worked for our org.

**Comment by rollarapp** [comment]
hope you are okay.

**Comment by rollarapp** [comment]
i invite all parties reading this to check with their most trusted security engineer on evaluating the security differences between this and competitors. this is not a pissing match, it's 50000+ users in our case that had things working and then the lights go out.

**Comment by rollarapp** [comment]
this chat is done from an HR perspective. beware.

**Comment by AndrewBarba** [comment]
Spam.
