### ISSUE TITLE
Does not work on node 18 and can't use with FCM

### ISSUE THREAD

**Issue by rollarapp** [AndrewBarba/apns2#72]
we have 50000 people who relied on this, switching to FCM is not easy. Also, you can't use a token that worked here on FCM.

we used easy-apn and the owner of this deleted the comment that we again had a working product. I'm trying to help others have a working solution. our smartest engineers (he, she, it) all agreed - easy-apn is a solution that works moving forward. Please have your own engineers give the codebase of each a look. That is only fair.

**Comment by rollarapp** [comment]
https://github.com/AndrewBarba/apns2/blob/d6cda80c62306254fca7ef34574901108588c88f/.github/workflows/test.yml 

only supported up to node 14.

**Comment by AndrewBarba** [comment]
Spam.
