### ISSUE TITLE
APNS-expiration header not added when value is 0

### ISSUE THREAD

**Issue by LarsDanau** [AndrewBarba/apns2#88]
According to [Apple documentation](https://developer.apple.com/documentation/usernotifications/sending-notification-requests-to-apns) it should be possible to add an `apns-expiration` header with value: 0

`If the value is 0, APNs attempts to deliver the notification only once and doesn’t store it.`

Issue is located at https://github.com/AndrewBarba/apns2/blob/740f5d9b48247a9755f1a520a4a4f88e817e6996/src/apns.ts#L97

Because the value is 0, it will not enter the statement, hence not adding the expiration header

**Comment by AndrewBarba** [comment]
Pushing a new version: https://github.com/AndrewBarba/apns2/commit/a0c453462923187702461c3a3d89022361833bfc

**Comment by AndrewBarba** [comment]
Released https://github.com/AndrewBarba/apns2/releases/tag/11.7.1
